export const headCellMap = new Map([
  ['index', 'Index'],
  ['registerNo', '등록번호'],
  ['createdAt', 'Time'],
  ['endTime', 'End Time'],
  ['day', '일차'],
  ['isCompleted', '완료 상태'],
  ['surveyActivityName', '설문 조사 모듈 이름'],
  ['surveyQuestion', '질문'],
  ['surveySequence', '문항 번호'],
  ['surveyAnswer', '문항 답변'],
  ['moodActivityName', '마음 상태 모듈 이름'],
  ['feelIntensity', '느낌 이름'],
  ['feelIntensityFloat', '느낌 강도'],
  ['mindStatus', '마음 종류'],
  ['mood', '감정어'],
  ['emotionalFactor', '감정 요인'],
  ['diaryActivityName', '마음 일기 모듈 이름'],
  ['reason', '감정의 이유'],
  ['actionFromEmotion', '감정의 촉발 이후 행동'],
  ['context', '자유 일기'],
  ['images', '사진'],
  ['todoActivityName', '할일 모듈 이름'],
  ['descriptionActivityName', '서술형 응답 모듈 아름'],
  ['description', '서술 내용'],
  ['sleep', '수면 상태'],
  ['stepCount', '걸음수'],
  ['distanceWalkingRunning', '이동거리(km)'],
  ['activeEnergyBurned', '칼로리 소비'],
  ['heartRate', '심박수'],
  ['heartRateMotion', '활동 수준'],
  ['hrv', 'HRV'],
]);
